# Generated by Django 4.1.2 on 2025-02-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nibble", "0010_alter_task_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("icon", models.CharField(default="🏠", max_length=5)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ScuffleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "nibbleProfile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nibble.nibbleprofile",
                    ),
                ),
            ],
        ),
    ]
