# Generated by Django 4.1.2 on 2025-02-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scuffle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scuffleprofile",
            name="clan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scuffle.clan",
            ),
            preserve_default=False,
        ),
    ]
