# Generated by Django 4.1.2 on 2025-02-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scuffle", "0002_scuffleprofile_clan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scuffleprofile",
            name="clan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scuffle.clan",
            ),
        ),
    ]
