# Generated by Django 4.1.2 on 2025-02-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scuffle", "0003_alter_scuffleprofile_clan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=250, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("has_finished", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="scuffleprofile",
            name="clan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="scuffle.clan",
            ),
        ),
        migrations.CreateModel(
            name="ClanSeasonRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_total", models.IntegerField()),
                ("rank", models.PositiveIntegerField()),
                ("out_of", models.PositiveIntegerField()),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_records",
                        to="scuffle.clan",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clan_records",
                        to="scuffle.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("points", models.IntegerField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="scuffle.scuffleprofile",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scuffle.season"
                    ),
                ),
            ],
        ),
    ]
